-- REFRESH CONTENT LIBRARY
TRUNCATE TABLE content_library;

-- INSERT CONTENT (User Provided)
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Sprouted Moong Curry', 'Protein-rich lentil stew.', 'utensils', ARRAY['jain','lunch','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Palak Dal Kichadi', 'Iron-packed nourishing khichdi.', 'leaf', ARRAY['jain','dinner','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Kuttu Chilla', 'Buckwheat pancakes energy boost.', 'utensils', ARRAY['jain','breakfast','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Pumpkin Seed Chikki', 'Sweet iron-rich snack.', 'cookie', ARRAY['jain','snack','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Spinach Potato Sabzi', 'Leafy greens sautéed.', 'utensils', ARRAY['jain','lunch','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Spinach Banana Smoothie', 'Iron and vitamin C boost.', 'droplet', ARRAY['vegan','breakfast','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Lentil Spinach Soup', 'Warm protein-packed soup.', 'droplet', ARRAY['vegan','dinner','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Beetroot-Spinach Salad', 'Fiber-rich fresh salad.', 'cherry', ARRAY['vegan','snack','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Quinoa Khichdi', 'High-protein one-pot meal.', 'leaf', ARRAY['vegan','dinner','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Tur Dal Soup', 'Rich turmeric lentil soup.', 'droplet', ARRAY['vegan','dinner','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Palak Paneer', 'Creamy spinach and cheese curry.', 'leaf', ARRAY['vegetarian','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Egg & Spinach Omelette', 'Protein and iron loaded.', 'utensils', ARRAY['vegetarian','breakfast','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Mixed Dal Tadka', 'Spiced lentil mix stew.', 'utensils', ARRAY['vegetarian','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Veggie-Pumpkin Soup', 'Warm vitamin-packed soup.', 'droplet', ARRAY['vegetarian','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Chia Berry Pudding', 'High-fiber chia dessert.', 'cookie', ARRAY['vegetarian','snack','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Chicken Spinach Curry', 'Lean protein & iron-rich stew.', 'fish', ARRAY['non_veg','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Egg Curry with Greens', 'Eggs with leafy curry.', 'fish', ARRAY['non_veg','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Fish Curry with Fenugreek', 'Protein-rich fish stew.', 'fish', ARRAY['non_veg','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Mutton Keema Palak', 'Seasoned mutton with spinach.', 'fish', ARRAY['non_veg','dinner','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Menstrual', 'Shakshuka Style Eggs', 'Eggs poached in tomato sauce.', 'utensils', ARRAY['non_veg','breakfast','muscle_gain','cramps','low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Gentle Yoga Stretch', 'Low impact flexibility.', 'wind', ARRAY['home_based','cardio','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Calming Breathing', 'Relaxation and calm.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Easy Walking', 'Light cardio and mood boost.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Prenatal Yoga Flow', 'Gentle stretching and mindfulness.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Pilates Core Roll', 'Low-intensity core strength.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Arm Circles', 'Gentle shoulder mobilization.', 'wind', ARRAY['home_based','cardio','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Neck Roll Stretches', 'Loosening tension.', 'wind', ARRAY['home_based','cardio','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Childs Pose Sequence', 'Knee to chest stretch.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Leg Elevation', 'Resting legs upward.', 'wind', ARRAY['home_based','cardio','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Seated Cat-Cow', 'Spinal mobility on mat.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Menstrual', 'Light Pilates Routine', 'Gentle core exercises.', 'wind', ARRAY['home_based','cardio','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Chamomile Tea & Rest', 'Comforting warm tea for cramps.', 'coffee', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Warm Bath with Epsom', 'Soothing soak to relax muscles.', 'bed', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Lavender Aromatherapy', 'Calming essential oil inhale.', 'heart', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Journaling Reflections', 'Write feelings and relieve stress.', 'list', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Bedtime Yoga Nidra', 'Guided sleep meditation.', 'moon', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Use Heating Pad', 'Direct heat on abdomen.', 'bed', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Soothing Music Session', 'Relax with calming melodies.', 'lightbulb', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Bedtime Routine', 'Consistent sleep schedule.', 'bed', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Menstrual', 'Nourishing Soup Break', 'Warm soup for comfort.', 'droplet', ARRAY['cramps','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Vegetable Upma', 'Carb-rich hearty breakfast.', 'utensils', ARRAY['jain','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Ragi Vermicelli', 'High-fiber millet dish.', 'utensils', ARRAY['jain','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Rajgira Roti with Dal', 'Buckwheat flatbread combo.', 'leaf', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Mixed Sprout Salad', 'Protein-packed fresh salad.', 'cherry', ARRAY['jain','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Fermented Dhokla', 'Gut-friendly fermented snack.', 'cherry', ARRAY['jain','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Vegetable Oats', 'Energizing savory oats.', 'utensils', ARRAY['vegan','breakfast','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Tofu Stir-Fry', 'Protein boost with veggies.', 'leaf', ARRAY['vegan','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Sattu Drink', 'Cooling protein-rich beverage.', 'droplet', ARRAY['vegan','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Chickpea Curry', 'Fiber and protein-rich curry.', 'utensils', ARRAY['vegan','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Mung Bean Khichdi', 'Balanced protein-carbs khichdi.', 'utensils', ARRAY['vegan','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Paneer Bhurji', 'Spiced scrambled paneer for protein.', 'leaf', ARRAY['vegetarian','breakfast','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Chicken & Veg Salad', 'Grilled chicken with greens.', 'cherry', ARRAY['vegetarian','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Egg Bhurji with Roti', 'Protein snack for strength.', 'utensils', ARRAY['vegetarian','breakfast','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Chole (Chickpea) Curry', 'High-protein legume curry.', 'utensils', ARRAY['vegetarian','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Mixed Dal Fry', 'Complex carb and protein mix.', 'utensils', ARRAY['vegetarian','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Grilled Chicken Salad', 'Lean protein with fresh salad.', 'cherry', ARRAY['non_veg','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Egg Fried Rice', 'Protein and carbs energizer.', 'utensils', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Lemon Pepper Fish', 'Zesty fish for energy.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Chicken Jalfrezi', 'Spicy chicken stir-fry.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Ragi Porridge', 'High fiber millet cereal.', 'utensils', ARRAY['jain','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Moong Dal Cheela', 'Protein pancake stuffed with veggies.', 'utensils', ARRAY['jain','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Coconut Chia Pudding', 'Omega-3 and fiber breakfast.', 'cookie', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Sattu Sharbat', 'Cooling chickpea drink.', 'coffee', ARRAY['vegan','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Egg Bhurji Wrap', 'Protein wrap for energy.', 'utensils', ARRAY['vegetarian','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Follicular', 'Fish Tikka', 'Grilled spiced fish.', 'fish', ARRAY['non_veg','snack','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Bodyweight Circuit', 'Full body strength set.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Outdoor Jog', 'Moderate cardio run.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Cycling Session', 'Steady pace cycling.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Pilates Power', 'Core strength training.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Interval Stair Climb', 'Stairs for cardio.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'HIIT Beginner', 'Short bursts of cardio.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Dumbbell Presses', 'Strength training weights.', 'dumbbell', ARRAY['home_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Dance Fitness', 'Fun cardio workout.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Swimming Laps', 'Cardio swim workout.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Resistance Band Flow', 'Strength band routine.', 'dumbbell', ARRAY['home_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Gym Circuit Training', 'Mixed cardio and strength.', 'wind', ARRAY['gym_based','cardio','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Rowing Machine', 'Total body cardio.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Kickboxing Basics', 'Beginner boxing moves.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Kettlebell Deadlift', 'Full body strength exercise.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Battle Ropes Slams', 'High energy rope work.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Follicular', 'Spin Class', 'Group cycling workout.', 'wind', ARRAY['gym_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Morning Sun Ritual', 'Short walk for vitamin D.', 'sun', ARRAY['low_energy']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Fermented Foods Snack', 'Yogurt or kimchi for gut health.', 'sun', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Goal-Setting Session', 'Plan and visualize ambitions.', 'list', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Cold Shower Energy', 'Revitalizing morning shower.', 'sun', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Green Smoothie Ritual', 'Energy-boosting drink routine.', 'coffee', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Create Vision Board', 'Visualize your goals.', 'list', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Gratitude Walk', 'Evening reflection walk.', 'moon', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Follicular', 'Laughing Yoga', 'Joyful breathing exercises.', 'heart', ARRAY['stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Cauliflower Sabzi', 'Antioxidant-rich veg delight.', 'leaf', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Beetroot Pulao', 'Protein-rich beet pulao.', 'utensils', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Makhana Curry', 'Lotus seed curry energizer.', 'utensils', ARRAY['jain','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Jowar Roti & Dal', 'Sorghum roti with lentil stew.', 'leaf', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Sprout & Veg Soup', 'Light energizing broth.', 'droplet', ARRAY['jain','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Quinoa Salad', 'Vitamin-packed quinoa bowl.', 'cherry', ARRAY['vegan','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Vegan Tofu Curry', 'Protein-rich tofu stew.', 'leaf', ARRAY['vegan','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Avocado Spinach Toast', 'Healthy fats and iron.', 'leaf', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Fruit Parfait', 'Antioxidant-rich yogurt and fruit.', 'cherry', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Buckwheat Dhokla', 'Iron-rich fermented snack.', 'utensils', ARRAY['vegan','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Grilled Paneer Skewers', 'High-protein summer snack.', 'leaf', ARRAY['vegetarian','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Mixed Veg Curry', 'Colorful nutrient-packed curry.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Eggplant & Potato Sabzi', 'Hearty veggie curry.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Kadhi Pakora', 'Yogurt curry with protein fritters.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Sprouted Moong Salad', 'Protein-dense spicy salad.', 'cherry', ARRAY['vegetarian','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Grilled Salmon', 'Omega-3 rich fish fillet.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Tandoori Chicken', 'Protein-rich spiced chicken.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Prawn Curry', 'Protein-packed prawn stew.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Chicken Tikka Salad', 'Grilled chicken on greens.', 'cherry', ARRAY['non_veg','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Amaranth Khichdi', 'Gluten-free iron-rich khichdi.', 'utensils', ARRAY['jain','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Kale Coconut Soup', 'Antioxidant leafy soup.', 'droplet', ARRAY['jain','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Berry Oat Bowl', 'Antioxidant-rich breakfast.', 'utensils', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Quinoa Veg Stir Fry', 'High protein veggie medley.', 'utensils', ARRAY['vegan','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Paneer Tikka Masala', 'Creamy high-protein curry.', 'leaf', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Spicy Lentil Soup', 'Hearty soup with chilies.', 'droplet', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Shrimp Stir-Fry', 'Quick protein stir fry.', 'fish', ARRAY['non_veg','lunch','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Ovulatory', 'Grilled Mackerel', 'Fatty fish rich in omega-3.', 'fish', ARRAY['non_veg','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'HIIT Kickboxing', 'High intensity boxing moves.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Spin Bike Sprint', 'Fast-paced cycling.', 'wind', ARRAY['gym_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Bootcamp Circuit', 'Intense mixed workout.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Heavy Weight Lifting', 'Muscle building routine.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Tabata Workout', 'High intensity intervals.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Plyometrics Blast', 'Jumping exercise set.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Sprint Intervals', 'Short distance sprints.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Kettlebell Swings', 'Full-body power workout.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Jump Rope HIIT', 'High-intensity rope session.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'CrossFit Challenge', 'Dynamic multi-exercise set.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Dumbbell Squats', 'Strength building lower body.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Climbing Stairs Run', 'Intense stair cardio.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Power Yoga', 'Dynamic yoga practice.', 'moon', ARRAY['gym_based','yoga']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Trail Running', 'Outdoor intensive run.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Resistance Sprint', 'Weighted sprint training.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Plyometric Lunges', 'Explosive leg jump lunges.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Barbell Clean & Press', 'Advanced strength move.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Mountain Climbers', 'Full-body cardio bursts.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Abs Circuit', 'Core strength routine.', 'dumbbell', ARRAY['home_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Stair Climber', 'High-intensity stair workout.', 'wind', ARRAY['gym_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Heavy Weight Lifting', 'Muscle building routine.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Climbing Stairs Run', 'Intense stair cardio.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Trail Running', 'Outdoor intensive run.', 'wind', ARRAY['home_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'CrossFit Challenge', 'Dynamic multi-exercise set.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Plyometrics Blast', 'Jumping exercise set.', 'zap', ARRAY['gym_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Jump Rope HIIT', 'High-intensity rope session.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Kettlebell Swings', 'Full-body power workout.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Dumbbell Squats', 'Strength building lower body.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Ovulatory', 'Plyometric Lunges', 'Explosive leg jump lunges.', 'zap', ARRAY['home_based','hiit','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Dance It Out', 'Expressive dance for joy.', 'heart', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Spa or Massage Night', 'Self-massage for relaxation.', 'heart', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Night Out with Friends', 'Socialize and have fun.', 'heart', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Creative Project', 'Paint, write, or craft flow.', 'lightbulb', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Affirmation Writing', 'Positive self-talk journaling.', 'heart', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Ovulatory', 'Play a Sport', 'Group game for fun exercise.', 'heart', ARRAY[]::text[]);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Sweet Potato Curry', 'Comforting high-fiber curry.', 'utensils', ARRAY['jain','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Methi Thepla', 'Fenugreek parathas for digestion.', 'utensils', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Vegetable Khichdi', 'Warm one-pot comfort food.', 'leaf', ARRAY['jain','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Banana Oats Porridge', 'Warm fiber-rich breakfast.', 'utensils', ARRAY['jain','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Peanut Chikki', 'Healthy fat and protein snack.', 'cookie', ARRAY['jain','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Mixed Vegetable Soup', 'Light, soothing broth.', 'droplet', ARRAY['vegan','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Sweet Potato Stew', 'Warm, nutrient-dense stew.', 'droplet', ARRAY['vegan','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Dal Soup', 'High-protein lentil soup.', 'droplet', ARRAY['vegan','dinner','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Turmeric Rice', 'Anti-inflammatory spiced rice.', 'utensils', ARRAY['vegan','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Almond Date Smoothie', 'Calming protein shake.', 'droplet', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Spinach Paneer Kofta', 'Protein-rich comfort bowl.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Vegetable Pulao', 'Balanced carb meal.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Buttermilk (Chaas)', 'Probiotic hydration drink.', 'coffee', ARRAY['vegetarian','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Ragi Laddu', 'Sweet, magnesium-rich treat.', 'cookie', ARRAY['vegetarian','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Yogurt with Fruit', 'Digestive, cooling snack.', 'cherry', ARRAY['vegetarian','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Chicken Soup', 'Soothing brothy protein soup.', 'droplet', ARRAY['non_veg','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Shrimp Curry', 'Protein-rich anti-inflammatory.', 'fish', ARRAY['non_veg','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Eggplant & Chicken Stew', 'Hearty blend stew.', 'utensils', ARRAY['non_veg','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Steamed Fish & Veggies', 'Light, easy-to-digest meal.', 'fish', ARRAY['non_veg','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Turkey Chili', 'High-protein, easy comfort.', 'utensils', ARRAY['non_veg','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Turmeric Latte', 'Spiced warm drink.', 'coffee', ARRAY['jain','snack']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Grilled Veg Sandwich', 'Complex carb comfort meal.', 'utensils', ARRAY['jain','lunch']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Curry Stew', 'Mixed vegetable curry.', 'utensils', ARRAY['vegan','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Banana Almond Smoothie', 'Calming high-protein drink.', 'droplet', ARRAY['vegan','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Methi Dal', 'Fenugreek lentil stew.', 'utensils', ARRAY['vegetarian','dinner']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('fuel', 'Luteal', 'Pumpkin Oats', 'Warm fiber-rich porridge.', 'utensils', ARRAY['vegetarian','breakfast']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Restorative Yoga', 'Gentle relaxation yoga.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Pilates Stretch', 'Soothing Pilates flow.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Balance Training', 'Stability and core work.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Leisure Swimming', 'Gentle pool exercise.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Elliptical Medium', 'Moderate pace cardio.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Gentle Cycling', 'Light indoor cycling.', 'wind', ARRAY['gym_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Slow Walk', 'Relaxing stroll.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Light Strength Set', 'Low weight strength.', 'dumbbell', ARRAY['gym_based','strength','muscle_gain']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Yoga Yin Poses', 'Deep stretch session.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Core Breathing', 'Mindful breathing focus.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Low Impact Aerobics', 'Gentle movement session.', 'wind', ARRAY['gym_based','cardio','weight_loss']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Evening Walk', 'Relaxation outdoor walk.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Yoga Twists', 'Detoxifying poses.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Ankle Circles', 'Gentle joint mobility.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Wall Sit', 'Static leg strength hold.', 'dumbbell', ARRAY['home_based','strength']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Light Jog', 'Relaxed jogging pace.', 'wind', ARRAY['home_based','cardio']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Tai Chi', 'Gentle flowing movements.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Yoga Flow Routine', 'Gentle full-body yoga.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('move', 'Luteal', 'Restorative Stretch', 'Slow deep stretches.', 'moon', ARRAY['home_based','yoga','stress_relief']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Chamomile Tea Before Bed', 'Promote restful sleep.', 'coffee', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Warm Milk with Turmeric', 'Soothing spiced drink.', 'coffee', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Evening Stretch Routine', 'Gentle body unwind.', 'moon', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Gratitude Journaling', 'Note positives and relax.', 'list', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Digital Device Curfew', 'Screens off an hour early.', 'lightbulb', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Meditative Breathing', 'Deep breaths to ease anxiety.', 'heart', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Sleep Hygiene Routine', 'Calm pre-bedtime ritual.', 'moon', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Foot Soak Ritual', 'Warm soak for tired feet.', 'bed', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Epsom Salt Bath', 'Mineral bath for relaxation.', 'bed', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Coloring Activity', 'Mindful coloring to unwind.', 'lightbulb', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Light Reading', 'Enjoy calming literature.', 'lightbulb', ARRAY['stress_relief','bloating']);
INSERT INTO content_library (category, phase, title, description, icon, tags) VALUES ('ritual', 'Luteal', 'Morning Stretch', 'Gentle yoga at sunrise.', 'moon', ARRAY['stress_relief','bloating']);
